### ISSUE TITLE
This browser/engine doesn't support BigInt64Array API.

### ISSUE THREAD

**Issue by Speed258** [LostBeard/BlazorWASMSIMDDetectExample#4]
This issue actively appears on Iphone 14 and older once simd is disabled by code it starts throw this error:
Error: Failed to start platform. Reason: Error: Assert failed: This browser/engine doesn't support BigInt64Array API.

.csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
    <PublishTrimmed>true</PublishTrimmed>
    <BlazorEnableCompression>true</BlazorEnableCompression>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Configurations>Debug;Release;ReleaseCompat;Staging</Configurations>
	  <!--<RunAOTCompilation>true</RunAOTCompilation>-->
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'ReleaseCompat' ">
    <WasmEnableSIMD>false</WasmEnableSIMD>
    <BlazorWebAssemblyJiterpreter>false</BlazorWebAssemblyJiterpreter>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Staging|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Append.Blazor.WebShare" Version="7.0.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Blazored.SessionStorage" Version="2.4.0" />
    <PackageReference Include="BuildWebCompiler2022" Version="1.14.10" />
    <PackageReference Include="Majorsoft.Blazor.Components.Notifications" Version="1.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.8" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Client" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NSwag.ApiDescription.Client" Version="14.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
    <PackageReference Include="Telegram.Bot.Extensions.LoginWidget" Version="1.2.0" />
  </ItemGroup>
</Project>
```

Source: https://webassembly.org/features/

Is there any solution to fix this issue?

**Comment by LostBeard** [comment]
I do not have access to an iPhone to try and reproduce the error. Is there any more error information you can share? Can you copy and paste the entire error? I am hoping there is some stack trace information in the error.

Edit: Never mind. I am to reproduce the error message by adding the code `delete globalThis.BigInt64Array` to my `index.html` file.

**Comment by LostBeard** [comment]
From the page you linked: [https://webassembly.org/features/](https://webassembly.org/features/)

> wasm-bigint is supported in desktop Safari since 14.1 and iOS Safari since 14.5; however BigInt64Array, which is needed by Emscripten, was released in 15

I'm not sure there is a way to work around this issue because it is a requirement of Emscripten.

**Comment by LostBeard** [comment]
Because I cannot test on a browser that does not support BigInt64Array, I am simply deleting the existing BigInt64Array, which then gives me the error you are seeing.

Code I added to the `<head>` section of my Blazor WASM `index.html` to reproduce the error you are seeing.  
(Obviously not the same as testing on the actual problem browser.)
```html
    <script>
        delete globalThis.BigInt64Array;
    </script>
```

Then I am able to get Blazor WASM to load by adding this to the `<head>` section of `index.html`. 
```html
    <script>
        globalThis.BigInt64Array ??= function () { };
    </script>
```

It seems unlikely that something as simple as that would fix your issue, but I am currently unable to find a BigInt64Array polyfill, which would likely be a better fix.

**Comment by Speed258** [comment]
So what is my options then?

**Comment by LostBeard** [comment]
Have you tried the possible solution I wrote in my previous post?

> Then I am able to get Blazor WASM to load by adding this to the `<head>` section of index.html.
```html
  <script>
        globalThis.BigInt64Array ??= function () { };
  </script>
```

**Comment by LostBeard** [comment]
I was able to test using BrowserStack.com as they have [Safari 14](https://www.browserstack.com/test-on-safari-browser-14) available. I do not have a paid account so testing is a pain... 

Safari 14 also does not support WASM exception handling so your .csproj needs the flag `WasmEnableExceptionHandling`  added to your ReleaseCompat build:
```xml
  <PropertyGroup Condition=" '$(Configuration)' == 'ReleaseCompat' ">
    <WasmEnableSIMD>false</WasmEnableSIMD>
    <BlazorWebAssemblyJiterpreter>false</BlazorWebAssemblyJiterpreter>
    <WasmEnableExceptionHandling>false</WasmEnableExceptionHandling>
  </PropertyGroup>
```

And in your Javascript SIMD detection code make sure it is using the compat build if WASM exception handling (or SIMD) is not supported:
```js
...
var supportsSimd = await wasmFeatureDetect.simd();
var supportsExceptions = await wasmFeatureDetect.exceptions();
var useCompatMode = !supportsExceptions || !supportsSimd;
...
```

And to bypass the exceptions caused by lack of BigInt64Array, add your `index.html` or before SIMD and WASM EH testing: 
```js
if (!globalThis.BigInt64Array) globalThis.BigInt64Array = function () { };
if (!globalThis.BigUint64Array) globalThis.BigUint64Array = function () { };
```

With these changes I was able to get my  Blazor WASM site (https://www.spawndev.com) to start in Safari 14, but it still had errors likely tied to other features of the site. 

I will try to build and publish a bare minimum site for testing these fixes but browserstack.com is a pain to use for free but appears to be my only option for testing on Safari 14 at the moment.

**Comment by LostBeard** [comment]
The below Blazor WASM example project works on Safari 14 using the methods I have described above. 
[BlazorWASMSafari14Compat](https://github.com/LostBeard/BlazorWASMSafari14Compat)

**Comment by LostBeard** [comment]
I updated this project, including the README.md instructions and I updated the demo build (link below.) Can you check on your iPhone 14?

[BlazorWASMSIMDDetectExample Demo](https://lostbeard.github.io/BlazorWASMSIMDDetectExample/)

It is working for me using [BrowserStack.com Safari 14](https://www.browserstack.com/test-on-safari-browser-14)

![Safari14Test](https://github.com/user-attachments/assets/4a57c5f2-62b7-4b43-8d4f-5320e7b28a65)
